export const FETCH_BLOCK = 'FETCH_BLOCKS';
export const FETCH_CHART = 'FETCH_CHART';
export const SEARCH_BLOCK_OR_TRANSACTION = 'SEARCH_BLOCK_OR_TRANSACTION';
export const GET_LATEST_BLOCKS = 'GET_LATEST_BLOCKS';